### ISSUE TITLE
Code fails in simple test case

### ISSUE THREAD

**Issue by searleser97** [valenpe7/bentley-ottmann#1]
This code is detecting just 1 intersection out of 2 intersections for the following test case:
```java
ArrayList<Segment> data = new ArrayList<>();
data.add(new Segment(new Point(0, 0), new Point(140, 130)));
data.add(new Segment(new Point(30, 60), new Point(50, 65)));
data.add(new Segment(new Point(10, 70), new Point(50, 90)));
data.add(new Segment(new Point(20, 80), new Point(130, 80)));
data.add(new Segment(new Point(110, 90), new Point(120, 85)));
data.add(new Segment(new Point(120, 100), new Point(130, 105)));
```
![image](https://user-images.githubusercontent.com/5056411/101115467-0c7a0300-35a9-11eb-9ffd-2a04a86ee8f6.png)

**Comment by valenpe7** [comment]
Hi @searleser97,

thanks for pointing this out. The algorithm, as described by Bentley and Ottmann, assumes that the following conditions are satisfied:

1. no two line segment endpoints or crossings have the same x-coordinate
2. no line segment endpoint lies upon another line segment
3. no three line segments intersect at a single point.

In your special case, the first condition is obviously **violated**. Please, find more about the special cases here: https://en.wikipedia.org/wiki/Bentley%E2%80%93Ottmann_algorithm#Special_position 

However, there exist certain solutions for handling special-position inputs. Feel free to extend the code!

**Comment by searleser97** [comment]
gotcha!, I'll see what can I do, thanks
